#!/usr/bin/python
import subprocess as sp
# get all pid that refeers to vconnector
from ps_utils import shell_cmd

process_lines = shell_cmd("ps -eo pid:10,rssize:10,vsz:10,uname:10,cmd | grep postgres | grep tpcv | sort -k2nr").split('\n')

for l in process_lines:
    if "tpcv" in l:
        if "idle" not in l and  "tpcv-data" not in l and "grep" not in l:
            print(l.split()[0])
            exit(0)

print(process_lines[0].split()[0])
exit(0)
