# This is the network config written by 'subiquity'
network:
  ethernets:
    enp1s0:
      dhcp4: true
      dhcp4-overrides:
        use-routes: false
    enp2s0:
      dhcp4: false
      addresses: [192.168.1.22/24]
      nameservers:
        addresses: [193.136.212.1, 193.136.212.21]
      routes:
       - to: default
         via: 192.168.1.1

  version: 2
