# This is the network config written by 'subiquity'
network:
    bridges:
        xenbr1:
            interfaces : []
            addresses: [172.16.0.1/16]
            parameters:
                stp: false

    ethernets:
        enp1s0:
            dhcp4: true
            dhcp4-overrides:
                use-routes: false
        enp2s0:
            dhcp4: true
    version: 2
